Repository AY2122S1-CS2103T-T12-2/tp, pull requests merged in 2021-11, with the labels that each got.

#160 Add About section to UG
  docs/UserGuide.md
  docs/images/export.png
  docs/images/layout.png
Labels: priority.High

#167 Bug fixes
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
Labels: type.Bug

#169 Add tests for `export`, `filter`, `rating`, etc.
  docs/team/marcuschj.md
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/CmdCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/SummaryCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/IsFilterablePredicate.java
  src/main/java/seedu/address/model/person/IsFindableContainsKeywordsPredicate.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/commons/util/FileUtilTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CmdCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/ExportCommandAllTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandNameTest.java
  src/test/java/seedu/address/logic/commands/SortCommandRatingTest.java
  src/test/java/seedu/address/logic/commands/SummaryCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/IsFilterablePredicateTest.java
  src/test/java/seedu/address/model/person/IsFindableContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/RatingTest.java
  src/test/java/seedu/address/model/person/ReviewTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.Medium

#180 Proofread UG
  docs/UserGuide.md
  docs/team/marcuschj.md
Labels: priority.Medium, type.UG

#177 Fix `filter` command
  src/main/java/seedu/address/model/contact/IsFilterablePredicate.java
  src/main/java/seedu/address/model/contact/Rating.java
  src/test/java/seedu/address/model/contact/IsFilterablePredicateTest.java
  src/test/java/seedu/address/model/contact/RatingTest.java
Labels: type.Bug, severity.High

#181 Update test cases
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: type.Task, priority.Medium

#187 Change UG usage scenarios to address third-person
  docs/AboutUs.md
  docs/UserGuide.md
  docs/images/johndoe.png
  docs/images/layout.png
  docs/images/team/imerbear.png
  docs/images/team/lethiciars.png
  docs/images/team/marcuschj.png
  docs/images/team/nataniayp.png
  docs/images/team/ryantianj.png
  docs/team/marcuschj.md
Labels: priority.Medium, type.UG

#191 Update DG individual parts (`export` feature, use cases and manual testing etc.)
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ExportActivityDiagram.puml
  docs/diagrams/ExportSequenceDiagram.puml
  docs/images/ExportActivityDiagram.png
  docs/images/ExportSequenceDiagram.png
  docs/team/marcuschj.md
Labels: priority.High

#192 Update DG — Find and Sort commands
  docs/DeveloperGuide.md
  docs/diagrams/FindActivityDiagram.puml
  docs/diagrams/SortActivityDiagram.puml
  docs/diagrams/SortSequenceDiagram.puml
  docs/images/FindActivityDiagram.png
  docs/images/FindSequenceDiagram.png
  docs/images/SortActivityDiagram.png
  docs/images/SortSequenceDiagram.png
  docs/team/nataniayp.md
Labels: priority.High

#201 Format DG and add Effort section
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/imerbear.md
  docs/team/lethiciars.md
  docs/team/marcuschj.md
Labels: priority.High

#202 Format DG
  docs/DeveloperGuide.md
  docs/team/marcuschj.md
Labels: priority.High

#205 Fix Sort Command
  src/main/java/seedu/address/model/contact/Rating.java
  src/main/java/seedu/address/model/contact/UniqueContactList.java
  src/test/java/seedu/address/model/contact/UniqueContactListTest.java
Labels: type.Bug, priority.High
